server:
  secret_key: "CHANGE_ME"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

ui:
  default_locale: "en"

doi_resolvers:
  doi.org: 'https://doi.org/'
default_doi_resolver: 'doi.org'

search:
  safe_search: 1
  formats:
    - html
    - json

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
  - name: mojeek
    engine: mojeek
    shortcut: mj

outgoing:
  request_timeout: 8.0
  max_connections: 10

botdetection:
  enabled: false
