server:
  secret_key: "CHANGE_ME"
  bind_address: "0.0.0.0"
  port: 8080

ui:
  default_locale: "en"

search:
  safe_search: 1
  formats:
    - json

engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
  - name: mojeek
    engine: mojeek
    shortcut: mj
  - name: duckduckgo_html
    engine: duckduckgo_html
    shortcut: ddgh

outgoing:
  request_timeout: 8.0
  max_connections: 10
